spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/sphzb?characterEncoding=utf-8
    username: root
    password: feng9402
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
server:
  servlet:
    context-path: /sphzb
mybatis:
  mapper-locations: classpath:mapper/*.xml