spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB
  datasource:
    url: jdbc:mysql://127.0.0.1/sphzb?characterEncoding=utf-8
    username: root
    password: feng9402
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
server:
  servlet:
    context-path: /sphzb
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  pattern:
    console: "%d - %msg%n"
  path: log/
  file: log/sphzb.log
  level:
    com.en.sphzb: debug